version: '3'
services:

  webapp:
    build: ./webapp
    container_name: factsheets-webapp
    environment:
      - ENV FS_MONGO_HOST=factsheets-mongo
      - ENV FS_MONGO_PORT=27017
    ports:
      - "5000:5000"
    expose:
      - 5000

  mongo:
    image: mongo:latest
    container_name: factsheets-mongo
    volumes:
      - ${FS_MONGO_PATH}:/data/db
    ports:
      - "27017:27017"


